.TH cbcpart 8 "Version 0.2: 05 January 2016" "CMDB suite manuals" "cmdb, cbc and dnsa collection"
.SH NAME
cbcpart \- Create Build Config Partitions
.SH SYNOPSIS
.B cbcpart
[
.B action
] [
.B selection
] [
.B details
] [
.B partition info
]

.B cbcpart
[
.B -adlmrv
] [
.B -p | -s | -o
] [
.B -bogun
] [
.B -tfixy
]

.SH DESCRIPTION
\fBcbcpart\fP is software to manipulate partition schemes for the build system.
You can add add a scheme, display a specific scheme, list all schemes or remove
a specific scheme.
Once you have added a scheme name, you can then define partitions to add to the
scheme, or remove partitions from the scheme.
You can also configure partition schemes to use \fBLVM\fP, the Logical Volume
Manager for more flexible partition arangements.

.SH OPTIONS
.B action
.IP "-a,  --add"
add a partition or scheme.
.IP "-d,  --display"
display partitions in a scheme.
.IP "-l,  --list"
list all partition schemes.
.IP "-m,  --modify"
modify a scheme / partition.
.IP "-r,  --remove, --delete"
remove a partition from a scheme or an entire partition scheme.
.IP "-v,  --version"
version (no other argument needed)
.IP "-h,  --help"
display a short help message
\fBNote\fP: these options are mutually exclusive.
.PP
.B selection
.IP "-p,  --partition"
work on a partition.
.IP "-s,  --scheme"
work on a scheme.
.IP "-o,  --option"
work on a partition option.

.PP
.B details
.IP "-u,  --lvm"
when adding a partition scheme, this option marks the scheme as using LVM.
.IP "-g,  --logical-volume \fBlog vol name\fP"
the name for the logical volume.
.IP "-n,  --scheme-name \fBscheme name\fP"
the name of the partition scheme.
.IP "-b,  --option \fBoption\fP"
you can use this to supply a mount option for the partition
.PP
.B partition information
.IP "-f,  --file-system \fBfile system type\fP"
the file system type for the partition
.IP "-t,  --mount-point \fBmount-point\fP"
the mount point of the partition
.IP "-i,  --min-size \fBminimum size\fP"
the minimum size of the partition
.IP "-x,  --max-size \fBmaximum size\fP"
the maximum size of the partition
.IP "-y,  --priority \fBpriority\fP"
the priority given to a partition when determining it's size
.PP
If you do not wish to use the min,max,priority scheme, just specify the maximum
size. The minimum will be set to this value and priority assigned a default
value of 100.
.PP
If \fBcbcpart\fP has been compiled with \fIlibpcre\fP support then there will
be checks against the validity of names of the scheme and logical volume, as
well as against the mount point and filesystem type. It is best to keep them all
lower case.
.PP
.SH FILES
.I /etc/dnsa/dnsa.conf
.RS
The system wide configuration file for the cmdb / dnsa / cbc suite of
programs. See
.BR dnsa.conf (5)
for further details.
.RE
.I ~/.dnsa.conf
.RS
User configuration for the cmdb / dnsa / cbc suite of programs. See
.BR dnsa.conf (5)
for further details.
.RE
.SH ENVIRONMENT
This suite of programs do not make use of environment variables at present
although this may change in the future. Watch this space!
.SH AUTHOR 
Iain M Conochie <iain-at-thargoid-dot-co-dot-uk>
.SH "SEE ALSO"
.BR dnsa(8),
.BR cbc(7),
.BR cbc(8),
.BR cbcdomain(8),
.BR cbclocale(8),
.BR cbcos(8),
.BR cbcvarient(8)
