FROM php:7.4-cli

USER root

RUN apt-get update -y
RUN apt-get install -y build-essential autoconf automake git libtool
RUN apt-get install -y libgcrypt20-dev libsqlite3-dev libmariadb-dev libvirt-dev libyaml-dev libxml2-dev uuid-dev unixodbc-dev libmariadb-dev-compat
