#
#
# Makefile for DNSA c programs
#
#
RM = rm -f
ECHO = echo
DIR = src
DAEMONDIR = daemon
CLIENTDIR = client
SUBDIRS = src daemon
bin_PROGRAMS = dnsa cmdb cbc cbcdomain cbcos cbcvarient cbcpart cpc cbcsysp cbcscript
sbin_PROGRAMS = cmdbd

all:	$(bin_PROGRAMS) $(sbin_PROGRAMS)

$(bin_PROGRAMS):
	$(MAKE) -C $(DIR) $@

$(sbin_PROGRAMS):
	$(MAKE) -C $(DAEMONDIR) $@

clean :
	for dir in $(SUBDIRS); do \
	  $(MAKE) -C $$dir clean; \
	done
