#
#
# Makefile for DNSA c programs
#
#
RM = rm -f
ECHO = echo
DIR = src
DAEMONDIR = daemon
CLIENTDIR = client
LIBDIR = lib
SUBDIRS = lib src daemon
bin_PROGRAMS = dnsa cmdb cbc cbcdomain cbcos cbcvarient cbcpart cpc cbcsysp cbcscript ckc cbclocale cmdb2
sbin_PROGRAMS = cmdbd ailsa cmdbc
lib_LIBRARIES = libailsacmdb.a libailsasql.a

all:	$(lib_LIBRARIES) $(bin_PROGRAMS) $(sbin_PROGRAMS)

libs:	$(lib_LIBRARIES)

daemon:	$(sbin_PROGRAMS)

$(lib_LIBRARIES):
	$(MAKE) -C $(LIBDIR) $@

$(bin_PROGRAMS):	$(lib_LIBRARIES)
	$(MAKE) -C $(DIR) $@

sqlt:
	$(MAKE) -C $(DIR) $@

$(sbin_PROGRAMS):	$(lib_LIBRARIES)
	$(MAKE) -C $(DAEMONDIR) $@

clean :
	for dir in $(SUBDIRS); do \
	  $(MAKE) -C $$dir clean; \
	done
