
- name: Configure network interface
  become: true
  template:
    src: interface.j2
    dest: "/etc/network/interfaces.d/{{ item.interface }}.cfg"
    owner: root
    group: root
    mode: 0644
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.interface }}"
  register: network_interface

# We are using 2 lists here. In order to loop over them sequentially
# we need to use this syntax in the loop command. We can then reference
# the lists with 0 being interfaces, and 1 being network_interface.results

- name: Bring up new network interface
  become: true
  command: "/usr/sbin/ifup {{ item.0.interface }}"
  loop: "{{ interfaces|product(network_interface.results)|list }}"
  loop_control:
    label: "{{ item.0.interface }}"
  when: item.1.changed == true
