---

- name: Grab Debian packages list
  include_vars: debian-packages.yml
  when: ansible_distribution == 'Debian'

- name: Grab Ubuntu packages list
  include_vars: ubuntu-packages.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install server packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Install library packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ libraries }}"
