#
#
# Makefile for CMDBD c programs
#
#

CC = gcc
RM = rm -f
override CFLAGS := -ansi -std=c99 -pedantic -O0 -W -Wall -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Wunused -g -D_GNU_SOURCE
LDFLAGS = -L../lib/ -L/usr/lib/mysql -L/usr/lib/x86_64-linux-gnu
override CPPFLAGS := -I../src/ -I../include/ -I/usr/include/mysql -I/usr/include/uuid `libgcrypt-config --cflags`
LDLIBS = -lgcrypt -lailsasql -lailsacmdb -lpcre -lmysqlclient -lsqlite3 -luuid -lyaml
#bin_PROGRAMS = ailsa
sbin_PROGRAMS = cmdbd cmdbc

SOBJECTS = client_info.o
CDOBJECTS = cmdbd.o
COBJECTS = cmdbc.o
AOBJECTS = ailsa.o conversion.o fileio.o

all:	$(sbin_PROGRAMS) $(bin_PROGRAMS)
cmdbd:	$(SOBJECTS) $(CDOBJECTS)
cmdbc:	$(COBJECTS) $(SOBJECTS)

$(sbin_PROGRAMS):
	$(LINK.o) $@.o $(SOBJECTS)  $(LDLIBS) -o $@

ailsa:	$(AOBJECTS)
	$(LINK.o) $(AOBJECTS) $(DBOBJECTS)  $(LDLIBS) -o $@

.PHONY:	clean

clean:
	$(RM) *.o $(sbin_PROGRAMS) $(bin_PROGRAMS)

