override CFLAGS := $(CFLAGS) -ansi -std=c99 -pedantic -O0 -W -Wall -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Wunused -g -D_XOPEN_SOURCE=700
override CPPFLAGS := -I../src/ -I../include/ -I/usr/include/uuid/

lib_LIBRARIES = libailsacmdb.a

libailsacmdb.a:	libailsacmdb.a(hash.o) libailsacmdb.a(ailsacmdb.o) \
		libailsacmdb.a(logging.o) libailsacmdb.a(data.o) \
		libailsacmdb.a(uuid.o) libailsacmdb.a(config.o) \
		libailsacmdb.a(list.o)

libailsacmdb.a(ailsacmdb.o):	ailsacmdb.o
	$(AR) $(ARFLAGS) $@ $<

libailsacmdb.a(logging.o):	logging.o
	$(AR) $(ARFLAGS) $@ $<

libailsacmdb.a(hash.o):	hash.o
	$(AR) $(ARFLAGS) $@ $<

libailsacmdb.a(list.o):	list.o
	$(AR) $(ARFLAGS) $@ $<

libailsacmdb.a(data.o):	data.o
	$(AR) $(ARFLAGS) $@ $<

libailsacmdb.a(uuid.o):	uuid.o
	$(AR) $(ARFLAGS) $@ $<

libailsacmdb.a(config.o): config.o
	$(AR) $(ARFLAGS) $@ $<

.PHONY:	clean

clean:
	$(RM) *.o *.a
