#
#
# Makefile for DNSA c programs
#
#

CC = gcc
RM = rm -f
CFLAGS = -ansi -std=c99 -pedantic -O0 -W -Wall -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Wunused -g -D_POSIX_C_SOURCE=200809L
CPPFLAGS = -I/usr/include/mysql
LDFLAGS = -L/usr/lib/mysql -L/usr/lib/x86_64-linux-gnu
PCLIBS = -lpcre
LIBS = -lmysqlclient $(PCLIBS) -lsqlite3
bin_programs = dnsa cmdb cbc cbcdomain cbcos cbcvarient cbcpart cpc cbcsysp cbcscript ckc

SOBJECTS = errors.o checks.o cmdb_data.o
COMOBJECTS = cbc_data.o cbc_base_sql.o cbc_common.o cbccom.o
DNSCOMOBJ = dnsa_net.o dnsa_base_sql.o zones.o dnsacom.o dnsa_data.o
DBOBJECTS = cbc_base_sql.o dnsa_base_sql.o base_sql.o cmdb_base_sql.o
COBJECTS = cmdb.o cmdbcom.o $(SOBJECTS) servers.o customers.o cmdb_base_sql.o base_sql.o
DOBJECTS = dnsa.o $(SOBJECTS) $(DNSCOMOBJ) base_sql.o
BOBJECTS = cbc.o $(SOBJECTS) $(COMOBJECTS) $(DNSCOMOBJ) build.o createbuild.o cbc_dnsa.o base_sql.o
CDOBJECTS = cbcdomain.o $(SOBJECTS) $(COMOBJECTS) $(DNSCOMOBJ) cbcnet.o cbc_dnsa.o base_sql.o
COOBJECTS = cbcos.o $(SOBJECTS) $(COMOBJECTS) base_sql.o cbcnet.o
CVOBJECTS = cbcvarient.o $(SOBJECTS) $(COMOBJECTS) base_sql.o
CKOBJECTS = cbcpart.o $(SOBJECTS) $(COMOBJECTS) base_sql.o
POBJECTS = cpc.c $(SOBJECTS)
KOBJECTS = ckc.c $(SOBJECTS)
SPOBJECTS = cbcsysp.o $(SOBJECTS) $(COMOBJECTS) base_sql.o
SSOBJECTS = cbcscript.o $(SOBJECTS) $(COMOBJECTS) base_sql.o
TOBJECTS = sql_test.o $(SOBJECTS)

COMHEADERS = cmdb.h cmdb_cbc.h cbc_data.h cbc_base_sql.h base_sql.h cbc_common.h
DHEADERS = cmdb_dnsa.h dnsa_base_sql.h base_sql.h cmdb.h checks.h
CHEADERS = cmdb_cmdb.h cmdb_base_sql.h base_sql.h cmdb.h checks.h cmdb_data.h
BHEADERS = $(COMHEADERS) checks.h build.h
CDHEADERS = $(COMHEADERS) cbc_dnsa.h cmdb_dnsa.h dnsa_base_sql.h
CVHEADERS = $(COMHEADERS) cbcvarient.h
CKHEADERS = $(COMHEADERS) cbcpart.h
PHEADERS = cmdb.h cmdb_cpc.h
KHEADERS = cmdb.h cmdb_ckc.h

all:	$(bin_programs)

dnsa:	$(DOBJECTS) $(DHEADERS)
	$(CC) $(CFLAGS) -o $@ $(DOBJECTS) $(LDFLAGS) $(LIBS)

cmdb:	$(COBJECTS) $(CHEADERS)
	$(CC) $(CFLAGS) -o $@ $(COBJECTS) $(LDFLAGS) $(LIBS)

cbc:	$(BOBJECTS) $(BHEADERS)
	$(CC) $(CFLAGS) -o $@ $(BOBJECTS) $(LDFLAGS) $(LIBS)

cbcdomain:	$(CDOBJECTS) $(CDHEADERS)
	$(CC) $(CFLAGS) -o $@ $(CDOBJECTS) $(LDFLAGS) $(LIBS)

cbcos:	$(COOBJECTS) $(COMMHEADERS)
	$(CC) $(CFLAGS) -o $@ $(COOBJECTS) $(LDFLAGS) $(LIBS)

cbcvarient:	$(CVOBJECTS) $(CVHEADERS)
	$(CC) $(CFLAGS) -o $@ $(CVOBJECTS) $(LDFLAGS) $(LIBS)

cbcpart:	$(CKOBJECTS) $(CKHEADERS)
	$(CC) $(CFLAGS) -o $@ $(CKOBJECTS) $(LDFLAGS) $(LIBS)

cpc:	$(POBJECTS) $(PHEADERS)
	$(CC) $(CFLAGS) -o $@ $(POBJECTS) $(PCLIBS)

ckc:	$(KOBJECTS) $(KHEADERS)
	$(CC) $(CFLAGS) -o $@ $(KOBJECTS) $(PCLIBS)

cbcsysp:	$(SPOBJECTS)
	$(CC) $(CFLAGS) -o $@ $(SPOBJECTS) $(LDFLAGS) $(LIBS)

cbcscript:	$(SSOBJECTS)
	$(CC) $(CFLAGS) -o $@ $(SSOBJECTS) $(LDFLAGS) $(LIBS)

.PHONY :	clean
clean :
	$(RM) *.o $(bin_programs)

