#
#
# Makefile for DNSA c programs
#
#

CC = gcc
RM = rm -f
override CFLAGS := $(CFLAGS) -ansi -std=c99 -pedantic -O0 -W -Wall -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Wunused -g -D_POSIX_C_SOURCE=200809L
override CPPFLAGS := $(CPPFLAGS) -I/usr/include/mysql -I../include/
override LDFLAGS := $(LDFLAGS) -L/usr/lib/mysql -L/usr/lib/x86_64-linux-gnu
PCLIBS = -lpcre
override LDLIBS := -lmysqlclient $(PCLIBS) -lsqlite3 -lvirt $(LDLIBS)
bin_programs = dnsa cmdb cbc cbcdomain cbcos cbcvarient cbcpart cpc cbcsysp cbcscript ckc cbclocale

SOBJECTS = errors.o checks.o cmdb_data.o
COMOBJECTS = cbc_data.o cbc_base_sql.o cbc_common.o cbccom.o
DNSCOMOBJ = dnsa_net.o dnsa_base_sql.o zones.o dnsacom.o dnsa_data.o
COBJECTS = cmdb.o cmdbcom.o $(SOBJECTS) servers.o customers.o cmdb_base_sql.o base_sql.o
DOBJECTS = dnsa.o $(SOBJECTS) $(DNSCOMOBJ) base_sql.o
BOBJECTS = cbc.o $(SOBJECTS) $(COMOBJECTS) $(DNSCOMOBJ) build.o createbuild.o cbc_dnsa.o base_sql.o
CDOBJECTS = cbcdomain.o $(SOBJECTS) $(COMOBJECTS) $(DNSCOMOBJ) cbcnet.o cbc_dnsa.o base_sql.o
COOBJECTS = cbcos.o $(SOBJECTS) $(COMOBJECTS) base_sql.o cbcnet.o
CVOBJECTS = cbcvarient.o $(SOBJECTS) $(COMOBJECTS) base_sql.o
CKOBJECTS = cbcpart.o $(SOBJECTS) $(COMOBJECTS) base_sql.o
CLOBJECTS = cbclocale.o $(SOBJECTS) $(COMOBJECTS) base_sql.o
POBJECTS = cpc.c $(SOBJECTS)
KOBJECTS = ckc.c $(SOBJECTS)
SPOBJECTS = cbcsysp.o $(SOBJECTS) $(COMOBJECTS) base_sql.o
SSOBJECTS = cbcscript.o $(SOBJECTS) $(COMOBJECTS) base_sql.o

COMHEADERS = cmdb.h cmdb_cbc.h cbc_data.h cbc_base_sql.h base_sql.h cbc_common.h
DHEADERS = cmdb_dnsa.h dnsa_base_sql.h base_sql.h cmdb.h checks.h
CHEADERS = cmdb_cmdb.h cmdb_base_sql.h base_sql.h cmdb.h checks.h
BHEADERS = $(COMHEADERS) checks.h build.h
CDHEADERS = $(COMHEADERS) cbc_dnsa.h cmdb_dnsa.h dnsa_base_sql.h
CVHEADERS = $(COMHEADERS)
PHEADERS = cmdb.h

all:	$(bin_programs)

dnsa:	$(DOBJECTS) $(LDLIBS)
$(DOBJECTS):	$(DHEADERS)

cmdb:	$(COBJECTS) $(LDLIBS)
$(COBJECTS):	$(CHEADERS)

cbc:	$(BOBJECTS) $(LDLIBS)
$(BOBJECTS):	$(BHEADERS)

cbcdomain:	$(CDOBJECTS) $(LDLIBS)
$(CDOBJECTS):	$(CDHEADERS)

cbcos:	$(COOBJECTS) $(LDLIBS)
$(COOBJECTS):	$(COMMHEADERS)

cbcvarient:	$(CVOBJECTS) $(LDLIBS)
$(CVOBJECTS):	$(CVHEADERS)

cbcpart:	$(CKOBJECTS) $(LDLIBS)
$(CKOBJECTS):	$(CVHEADERS)

cbclocale:	$(CLOBJECTS) $(LDLIBS)
$(CLOBJECTS):	$(CVHEADERS)

cpc:	$(POBJECTS) $(LDLIBS)

ckc:	$(KOBJECTS) $(LDLIBS)
$(POBJECTS) $(KOBJECTS) :	$(PHEADERS)

cbcsysp:	$(SPOBJECTS) $(LDLIBS)

cbcscript:	$(SSOBJECTS) $(LDLIBS)

.PHONY :	clean
clean :
	$(RM) *.o $(bin_programs)

