name: C/C++ CI

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup up build
      run: autoreconf -iv
    - name: Start configuration
      run: ./configure
    - name: Make Software
      run: make
    - name: Run checks
      run: make check
    - name: Run distbuild
      run: make distcheck
